# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0007_auto_20160219_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='pages.Page', verbose_name='Sites'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='additions',
            field=models.ManyToManyField(blank=True, related_name='tariff', to='lp.TariffAddition', verbose_name='Additions'),
        ),
        migrations.AlterField(
            model_name='tarifforder',
            name='additions',
            field=models.ManyToManyField(blank=True, to='lp.TariffAddition', verbose_name='Additions'),
        ),
    ]
