# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0008_auto_20160310_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='sites',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
