# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0009_auto_20160317_0550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountDown',
        ),
        migrations.RemoveField(
            model_name='request',
            name='config',
        ),
        migrations.RemoveField(
            model_name='request',
            name='site',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='form_config',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='site',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='additions',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='block',
        ),
        migrations.RemoveField(
            model_name='tarifforder',
            name='additions',
        ),
        migrations.RemoveField(
            model_name='tarifforder',
            name='site',
        ),
        migrations.RemoveField(
            model_name='tarifforder',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='block',
            name='form_config',
        ),
        migrations.RemoveField(
            model_name='block',
            name='offices',
        ),
        migrations.AlterField(
            model_name='block',
            name='order',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Sort ordering'),
        ),
        migrations.AlterField(
            model_name='block',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='pages.Page', verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Sort ordering'),
        ),
        migrations.AlterField(
            model_name='subblock',
            name='order',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Sort ordering'),
        ),
        migrations.DeleteModel(
            name='FormConfig',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='SiteConfig',
        ),
        migrations.DeleteModel(
            name='Tariff',
        ),
        migrations.DeleteModel(
            name='TariffAddition',
        ),
        migrations.DeleteModel(
            name='TariffOrder',
        ),
    ]
